### ISSUE TITLE
Is there a guide to run this locally?

### ISSUE THREAD

**Issue by lonelycode** [gmpetrov/databerry#17]
Is there a guide on what env variables to set to run this locally? Would use cloud but can't because of privacy /IT policy concerns.

**Comment by gmpetrov** [comment]
Not yet! It's coming soon I'm currently working on a detailed documentation website :)

**Comment by curtisshipley** [comment]
At least tell us what goes in the .env.

**Comment by iprithvitharun** [comment]
+1

**Comment by aseem2625** [comment]
Running in local and deployment steps are much helpful to give it a spin, and even modify and contribute.

**Comment by gmpetrov** [comment]
Done! Added some details to the README + .env.example
