### ISSUE TITLE
Issue: change conversation in chat is laggy

### ISSUE THREAD

**Issue by OdapX** [gmpetrov/databerry#196]
#196

**Comment by OdapX** [comment]
switch conversation is laggy in dev and prod.

https://www.loom.com/share/1c512883cec0407c9a861836c5c8a3d2?sid=ebfe9fc8-b680-4af1-9395-7adf39b31037

**Comment by AbhinawRatan** [comment]
Hey i am trying to set up the project in my locals can you please help i am facing some issues

**Comment by AbhinawRatan** [comment]
Building 0.0s (0/0)                                                                                  docker:default
[+] Running 8/8
 ✔ Container docker-pgdb-1         Running                                                                         0.0s
 ✔ Container docker-minio-1        Running                                                                         0.0s
 ✔ Container docker-maildev-1      Running                                                                         0.0s
 ✔ Container docker-redis-1        Running                                                                         0.0s
 ✔ Container docker-qdrant-1       Running                                                                         0.0s
 ✔ Container docker-pgadmin-1      Running                                                                         0.0s
 ✔ Container docker-init_bucket-1  Started                                                                         0.0s
 ✔ Container docker-redis-ui-1     Running                                                                         0.0s
(node:21244) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
