### ISSUE TITLE
Databerry API Down?

### ISSUE THREAD

**Issue by WarpWing** [gmpetrov/databerry#27]
Hello all!

I've been trying out Databerry and this thing is absolutely amazing! However, I've been trying to get the API to work so that I can query my agent but I keep getting 404s. Is querying agents only a premium feature?

```python
import json
import requests

def get_agent_response(agent_id, api_key, query):
    url = f'https://api.databerry.ai/agents/query/{agent_id}'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {api_key}',
    }
    data = {
        'query': query,
    }
    response = requests.post(url, headers=headers, data=json.dumps(data))
    return response

def main():
    agent_id = 'xxxxx'  
    api_key = 'xxxx'  
    query = 'xxx'

    response = get_agent_response(agent_id, api_key, query)
    if response.status_code == 200:
        print(response.json())
    else:
        print(f"Error: received status code {response.status_code}")

if __name__ == '__main__':
    main()

```

**Comment by gmpetrov** [comment]
Should be fixed now, can you try again?

**Comment by WarpWing** [comment]
> Should be fixed now, can you try again?

Now it gives me a 402. Are API calls only with paid plans?

**Comment by WarpWing** [comment]
> Should be fixed now, can you try again?

That fixed it! It gave me a usage limit error probably because I used up all 20 calls. Thanks for the assistance!
