### ISSUE TITLE
error when submiting a question to the chat 

### ISSUE THREAD

**Issue by Louvivien** [gmpetrov/databerry#31]
Hi, 

This is what I see when I ask something in the chat:
AxiosError: Request failed with status code 404

This is what I get in the terminal:
```
event - compiled successfully in 509 ms (619 modules)
wait  - compiling /api/agents/[id]/query (client and server)...
event - compiled successfully in 493 ms (785 modules)
AxiosError: Request failed with status code 404
    at settle (webpack-internal:///(api)/./node_modules/.pnpm/axios@1.3.4/node_modules/axios/lib/core/settle.js:24:12)
    at Unzip.handleStreamEnd (webpack-internal:///(api)/./node_modules/.pnpm/axios@1.3.4/node_modules/axios/lib/adapters/http.js:584:71)
    at Unzip.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
```

When I go here:
http://localhost:3000/api/agents/clh9olhpl0001vnvlf5ay39sa/query
This is what I get:
not found

When I go here:
http://localhost:3000/api/agents
This is what I get:
[{"id":"clh9olhpl0001vnvlf5ay39sa","name":"vivien","description":"vivien","prompt":"As a customer support agent, please provide a helpful and professional response to the user's question or issue.","visibility":"private","ownerId":"clh7nm4fn0000vlnhf75ienzd","nbQueries":0,"interfaceConfig":{},"createdAt":"2023-05-04T22:10:54.829Z","updatedAt":"2023-05-04T22:10:54.829Z","tools":[{"id":"clh9olhpp0003vlvntpt9rf4e","type":"datastore","datastoreId":"clh7q9ipr0002vlbmda6d41i8"}]}]

Do you know why I get this error?

**Comment by gmpetrov** [comment]
Hello http://localhost:3000/api/agents/clh9olhpl0001vnvlf5ay39sa/query expect a POST request, when you navigate to this URL it's a GET request so that's why you're getting a 404

**Comment by Louvivien** [comment]
Thanks it must have been a misconfiguration. I reinstalled and it works
