### ISSUE TITLE
Pricing section view not clear

### ISSUE THREAD

**Issue by snehilsanyal** [gmpetrov/databerry#38]
I am on my Chrome browser, don't know why other pricing options are not visible to me. 

![image](https://github.com/gmpetrov/databerry/assets/41544905/c1150689-7901-4b1d-9f6a-9e51aa564b4b)

**Comment by snehilsanyal** [comment]
When I click on the other option, it prompts me to login. But I think it should be having same format, or atleast lesser contrast so that all pricing options are visible?

**Comment by gmpetrov** [comment]
Fixed! It was a dark mode / light mode conflict
Thx!
