### ISSUE TITLE
Crisp: Use like Magic Replay

### ISSUE THREAD

**Issue by marc-on-github** [gmpetrov/databerry#62]
My idea was to write a Chrome plugin that accesses the API from you.
However, I can not pass the existing chat history reasonably. Do you have an idea?
I don't like the behavior in the original chat client of Crips with your plugin. The first question works fine, the second one has to be entered in a box, users don't understand that.

**Comment by gmpetrov** [comment]
The UX of the Crisp plugin has changed 

<img width="442" alt="Screenshot 2023-06-02 at 13 19 02" src="https://github.com/gmpetrov/databerry/assets/4693180/ceb1e6ab-edc2-4ef0-8132-c8677bb7c610">

**Comment by marc-on-github** [comment]
Wow, that's great news. That's wonderful, with the history it's perfect.
