### ISSUE TITLE
FR: Export chatbot conversations

### ISSUE THREAD

**Issue by mimalef70** [gmpetrov/databerry#89]
![Image](https://github.com/gmpetrov/databerry/assets/4693180/61d241e2-04fd-4c3b-b3de-7770e0f829fd)

**Comment by gmpetrov** [comment]
API endpoint 
/api/conversations/export

- authenticated endpoint
- returns zip file containing a csv file for each conversations
exemple:

conversations.zip
- ID_42.csv
    - id_message1 ... all fields
- ID_44.csv. ...
